name: Test Coverage

on:
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/coverage.yml
  push:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/coverage.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        check-latest: true
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-cov
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: pytest . --cov --cov-report xml:main.xml

    - name: Upload Code Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: |
          main.xml